/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Int,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Summary = IDL.Record({
  'categoryBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'expenseCount' : IDL.Nat,
  'lowestExpense' : IDL.Opt(IDL.Float64),
  'totalExpense' : IDL.Float64,
  'highestExpense' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Int],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([IDL.Int], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getSummary' : IDL.Func([], [Summary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Int,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Summary = IDL.Record({
    'categoryBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'expenseCount' : IDL.Nat,
    'lowestExpense' : IDL.Opt(IDL.Float64),
    'totalExpense' : IDL.Float64,
    'highestExpense' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Int],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([IDL.Int], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getSummary' : IDL.Func([], [Summary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };